### ISSUE TITLE
DDMM decimal seconds do not get recognized

### ISSUE THREAD

**Issue by dshorthouse** [kristianmandrup/geo_point#2]
I have a batch of coordinates expressed as eg 43° 51' 45.12345" N, 120° 51' 19.333" W. Unfortunately, the decimal seconds result in failed parsing and GeoPoint.new returns nil for lat and lng.

**Comment by kristianmandrup** [comment]
You are most welcome to patch the parsing code and submit a PR. Haven't worked on this project for years... Hope it works out for you ;)
